version: '3'
services:
    mongo:
        image: mongo:5.0.10
        ports:
          - 27017:27017
        environment:
          - MONGO_INITDB_ROOT_USERNAME=login
          - MONGO_INITDB_ROOT_PASSWORD=password
