name: build

on:
    push:
        branches:
          - '**'

jobs:
    build_server:

      runs-on: ubuntu-latest
      
      steps:
        
        - uses: actions/checkout@v2
          with:
              persist-credentials: false
              fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16.14.0

        - run: cd server && yarn && ./test.sh
    
    build_client:

      runs-on: ubuntu-latest
      
      steps:
        
        - uses: actions/checkout@v2
          with:
              persist-credentials: false
              fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16.14.0

        - run: cd client && yarn && yarn test
