name: build

on:
    push:
        branches:
          - '**'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    build_server:

      runs-on: ubuntu-latest
      
      steps:
        
        - uses: actions/checkout@v2
          with:
              persist-credentials: false
              fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16.14.0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        - run: cd server && yarn && ./test.sh
    
    build_client:

      runs-on: ubuntu-latest
      
      steps:
        
        - uses: actions/checkout@v2
          with:
              persist-credentials: false
              fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16.14.0

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        - run: cd client && yarn && yarn test

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: ./server/
          push: true
          tags: latest
          labels: latest